M48
; DRILL file {KiCad 8.0.2-8.0.2-0~ubuntu22.04.1} date 2024-06-07T15:14:49-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-07T15:14:49-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-8.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X72.96Y-26.59
T2
X29.0Y-29.0
X29.0Y-67.0
X86.0Y-29.0
X86.0Y-67.0
M30
